version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5525
      POSTGRES_DB: postgres